### ISSUE TITLE
*** Unhandled NullPointerException: startup failure

### ISSUE THREAD

**Issue by KryptialGaming** [yugecin/opsu-dance#281] opened 2019-08-27 13:40 UTC
at itdelatrisu.opsu.db.BeatmapDB.init(BeatmapDB.java:139)
	at itdelatrisu.opsu.db.DBController.init(DBController.java:44)
	at yugecin.opsudance.OpsuDance.initDatabase(OpsuDance.java:86)
	at yugecin.opsudance.OpsuDance.start(OpsuDance.java:38)
	at yugecin.opsudance.core.Entrypoint.main(Entrypoint.java:80)

```
**info dump**
```
> DisplayContainer dump
OpenGL version: null(null)
state is null!

```

**Comment by yugecin** [comment] 2019-08-27 13:46
you didn't copy everything from the crash report

**Comment by yugecin** [comment] 2019-08-27 14:46
thanks, closing & linking duplicate #262

**Closed by yugecin** 2019-08-27 14:46 UTC

**Comment by yugecin** [comment] 2019-08-27 14:52
@KryptialGaming is there another error trace right above that one in the log file (.opsu.log)? it should give information about the root cause because this is a crash in the errorhandler >.<
