### ISSUE TITLE
Some note in the map IAHN - Transform [Aspire] dont render and the cursor just sits and spins

### ISSUE THREAD

**Issue by Name-The-Best** [yugecin/opsu-dance#39] opened 2016-10-19 11:59 UTC
[here's](https://my.mixtape.moe/tppsty.gif) a gif of it

**Comment by yugecin** [comment] 2016-12-09 07:55
> McKay: also, the bug here for the slidertime being too long: http://trigger.s-ul.eu/9zWIkcto.mp4
that's because peppy clamps the msPerBeat to between 10 and 1000 (and not clamping it results in too long sliders on such maps) in the timingpoints(edited)

**Comment by yugecin** [comment] 2016-12-09 20:55
stuff not rendering is caused by the breaks

**Comment by yugecin** [comment] 2016-12-10 00:36
fixed in c0acb7a

**Closed by yugecin** 2016-12-10 00:36 UTC
Labels: bug, low

**Comment by yugecin** [comment] 2016-12-10 09:50
also fixed in upstream: itdelatrisu/opsu#209
