### ISSUE TITLE
Failed to destroy OpenAL.

### ISSUE THREAD

**Issue by wang940824** [yugecin/opsu-dance#154] opened 2017-08-21 10:44 UTC
**Version:** 0.4.2
**Build date:** 2016-12-13 15:49
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_111
**OpenGL Version:** 1.4.0 - Build 8.14.10.2117 (Intel)
**Error:** `Failed to destroy OpenAL.`
**Stack trace:**
```
org.newdawn.slick.SlickException: Could not clear SoundStore sources, err: 40964
	at itdelatrisu.opsu.audio.MusicController.destroyOpenAL(MusicController.java:493)
	at itdelatrisu.opsu.audio.MusicController.reset(MusicController.java:455)
	at itdelatrisu.opsu.Container.close_sub(Container.java:134)
	at itdelatrisu.opsu.Container.start(Container.java:73)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:218)
```

**Comment by yugecin** [comment] 2017-08-22 07:26
Duplicate of #153

**Closed by yugecin** 2017-08-22 07:26 UTC
Labels: duplicate
